package xyz.oiio.n8n.service.workflow;

import jakarta.persistence.EntityManager;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import xyz.oiio.n8n.entity.TagEntity;
import xyz.oiio.n8n.entity.User;
import xyz.oiio.n8n.entity.WorkflowEntity;
import xyz.oiio.n8n.repository.ProjectRepository;
import xyz.oiio.n8n.repository.TagRepository;
import xyz.oiio.n8n.repository.WorkflowRepository;
import xyz.oiio.n8n.util.NanoIdGenerator;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class WorkflowService {

    private final WorkflowRepository workflowRepository;
    private final ProjectRepository projectRepository;
    private final TagRepository tagRepository;
    private final EntityManager entityManager;

    @Transactional
    public WorkflowEntity createWorkflow(WorkflowRequest request, User owner) {
        // Check if workflow name already exists for user
        if (workflowRepository.existsByNameAndOwner(request.getName(), owner)) {
            throw new IllegalArgumentException("Workflow name already exists: " + request.getName());
        }

        // Don't set ID - let @GeneratedValue create it automatically
        WorkflowEntity workflow = WorkflowEntity.builder()
                .name(request.getName())
                .description(request.getDescription())
                .active(false)
                .isArchived(false)
                .nodes(request.getNodes())
                .connections(request.getConnections())
                .settings(request.getSettings())
                .staticData(request.getStaticData())
                .meta(request.getMeta())
                .versionId(UUID.randomUUID().toString())
                .versionCounter(0)
                .triggerCount(0)
                .pinData(request.getPinData())
                .owner(owner)
                .projectId(request.getProjectId().filter(id -> id.matches("\\d+"))
                        .map(Long::parseLong)
                        .orElse(null))
                .tags(getTagsFromNames(request.getTagNames()))
                .build();

        // Use persist() for new entities - ID will be generated by @GeneratedValue
        entityManager.persist(workflow);
        entityManager.flush();
        log.info("Created new workflow with id: {}", workflow.getId());
        return workflow;
    }

    private static final int MAX_RETRIES = 3;

    @Transactional
    public WorkflowEntity updateWorkflow(String workflowId, WorkflowRequest request) {
        return updateWorkflowWithRetry(workflowId, request, 0);
    }

    private WorkflowEntity updateWorkflowWithRetry(String workflowId, WorkflowRequest request, int attempt) {
        try {
            // Load workflow in current transaction (attached state)
            WorkflowEntity workflow = workflowRepository.findById(workflowId)
                    .orElseThrow(() -> new NotFoundException("Workflow not found with id: " + workflowId));

            if (!workflow.getName().equals(request.getName()) &&
                    workflowRepository.existsByNameAndOwner(request.getName(), workflow.getOwner())) {
                throw new IllegalArgumentException("Workflow name already exists: " + request.getName());
            }

            // Update fields on attached entity (managed state)
            workflow.setName(request.getName());
            workflow.setDescription(request.getDescription());
            workflow.setNodes(request.getNodes());
            workflow.setConnections(request.getConnections());
            workflow.setSettings(request.getSettings());
            workflow.setStaticData(request.getStaticData());
            workflow.setMeta(request.getMeta());
            workflow.setPinData(request.getPinData());
            workflow.setVersionCounter(workflow.getVersionCounter() + 1);
            workflow.setVersionId(UUID.randomUUID().toString());

            workflow.setProjectId(request.getProjectId().filter(id -> id.matches("\\d+"))
                    .map(Long::parseLong)
                    .orElse(workflow.getProjectId()));

            // Update tags
            workflow.setTags(getTagsFromNames(request.getTagNames()));

            // Save using JPA with @Version for optimistic locking
            WorkflowEntity savedWorkflow = workflowRepository.save(workflow);
            log.info("Updated workflow with id: {}", savedWorkflow.getId());
            return savedWorkflow;
        } catch (org.springframework.orm.ObjectOptimisticLockingFailureException
                | org.hibernate.StaleObjectStateException e) {
            if (attempt < MAX_RETRIES) {
                log.warn("Optimistic locking conflict on workflow {}, retrying... (attempt {})", workflowId,
                        attempt + 1);
                try {
                    Thread.sleep(50 * (attempt + 1)); // Exponential backoff
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                }
                return updateWorkflowWithRetry(workflowId, request, attempt + 1);
            }
            log.error("Failed to update workflow {} after {} retries due to concurrent modification", workflowId,
                    MAX_RETRIES);
            throw new RuntimeException("Workflow update failed due to concurrent modification. Please try again.", e);
        }
    }

    @Transactional
    public void deleteWorkflow(String workflowId) {
        // Use direct UPDATE to avoid concurrent modification issues
        workflowRepository.updateArchivedStatus(workflowId, true, LocalDateTime.now());
        log.info("Archived workflow with id: {}", workflowId);
    }

    @Transactional
    public WorkflowEntity activateWorkflow(String workflowId) {
        // Use direct UPDATE to avoid concurrent modification issues
        workflowRepository.updateActiveStatus(workflowId, true, LocalDateTime.now());
        log.info("Activated workflow with id: {}", workflowId);
        return getWorkflowById(workflowId);
    }

    @Transactional
    public WorkflowEntity deactivateWorkflow(String workflowId) {
        // Use direct UPDATE to avoid concurrent modification issues
        workflowRepository.updateActiveStatus(workflowId, false, LocalDateTime.now());
        log.info("Deactivated workflow with id: {}", workflowId);
        return getWorkflowById(workflowId);
    }

    @Transactional(readOnly = true)
    public WorkflowEntity getWorkflowById(String workflowId) {
        return workflowRepository.findById(workflowId)
                .orElseThrow(() -> new NotFoundException("Workflow not found with id: " + workflowId));
    }

    @Transactional(readOnly = true)
    public Page<WorkflowEntity> getWorkflowsByUser(User user, Pageable pageable) {
        return workflowRepository.findByOwnerAndIsArchivedFalse(user, pageable);
    }

    @Transactional(readOnly = true)
    public Page<WorkflowEntity> getAccessibleWorkflows(String userId, Pageable pageable) {
        return workflowRepository.findAccessibleWorkflows(userId, pageable);
    }

    @Transactional(readOnly = true)
    public List<WorkflowEntity> getWorkflowsByUser(User user) {
        return workflowRepository.findByOwnerAndIsArchivedFalse(user);
    }

    @Transactional(readOnly = true)
    public List<WorkflowEntity> getWorkflowsByProject(Long projectId) {
        if (projectId == null) {
            return List.of();
        }
        return workflowRepository.findByProjectIdAndIsArchivedFalse(projectId);
    }

    @Transactional(readOnly = true)
    public List<WorkflowEntity> getWorkflowsByTagName(String tagName) {
        return workflowRepository.findByTagName(tagName);
    }

    @Transactional
    public WorkflowEntity incrementTriggerCount(String workflowId) {
        // Use direct UPDATE to avoid concurrent modification issues
        workflowRepository.incrementTriggerCount(workflowId);
        return getWorkflowById(workflowId);
    }

    private List<TagEntity> getTagsFromNames(List<String> tagNames) {
        if (tagNames == null || tagNames.isEmpty()) {
            return List.of();
        }

        return tagNames.stream()
                .map(tagName -> tagRepository.findByName(tagName)
                        .orElseGet(() -> {
                            TagEntity newTag = new TagEntity();
                            newTag.setName(tagName);
                            return tagRepository.save(newTag);
                        }))
                .collect(Collectors.toList());
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public static class WorkflowRequest {
        private String name;
        private String description;
        private List<Map<String, Object>> nodes;
        private Map<String, Object> connections;
        private WorkflowEntity.WorkflowSettings settings;
        private Map<String, Object> staticData;
        private WorkflowEntity.WorkflowMeta meta;
        private Map<String, Object> pinData;
        private Optional<String> projectId = Optional.empty();
        private List<String> tagNames = List.of();
    }

    public static class NotFoundException extends RuntimeException {
        public NotFoundException(String message) {
            super(message);
        }
    }
}